function I=pairwise_comp (f1,f2,vio1,vio2,eps)

%% 1 means parent is better, while 0 otherwise 
I= (((vio1==0) & (vio2==0) &  (f1<f2)) |... 
                ( vio1~=0 & vio2~=0 & vio1<= eps &  vio2<= eps  & f1<f2) |...
                ( vio1==0 & vio2~=0) | ...
                ( vio1~=0 & vio2~=0 & vio1> eps &  vio2> eps  & vio1<vio2));
end